### ISSUE TITLE
怎么获取所有的ImageView的List

### ISSUE THREAD

**Issue by AndroidBreathing** [simplepeng/NineGridView#6]
怎么能拿到当前item中所有的ImageView的List呢
我看作者用的拖拽 最后的动画需要这个

**Comment by simplepeng** [comment]
@AndroidBreathing url的List还是ImageView的List？url的是自己传进去的啊

**Comment by AndroidBreathing** [comment]
Imageview的list，

**Comment by simplepeng** [comment]
@AndroidBreathing 把NineGridView的所有子View get出来，然后过滤出ImageView就行了
