### ISSUE TITLE
嵌套在Rv中，刷新一遍图片会闪烁

### ISSUE THREAD

**Issue by aaaaaaaazmx** [simplepeng/NineGridView#9]
有啥办法解决吗？

**Comment by simplepeng** [comment]
@alizhijun 很严重吗，贴个图看看，我也是在rv里面用的，感觉还好呀

**Comment by aaaaaaaazmx** [comment]
> @alizhijun 很严重吗，贴个图看看，我也是在rv里面用的，感觉还好呀

其实也还好，需要设置Rv的动画和这个加载的图片的动画一致就不会显得突兀，我之前是把Rv的动画给禁止了，所有显得图片刷新会突兀。

**Comment by simplepeng** [comment]
已更新`1.0.4`版本
